### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by victornpb** [vhf/v8-bailout-reasons#19]
A lot of stuff changed since Ignition and TurboFan, and this repository hasnt been updated since.
IMO a warning should be added, so people don't write code like for example voiding try-catch unescessarely when try-catch is the right decision.

**Comment by vhf** [comment]
Right, thanks! Fixed via 6ae2f5528d7c36157b1c5f39f1f34de0a3a76071

I [had promised](https://news.ycombinator.com/item?id=16576018) to do this but didn't get around to actually doing it. Thanks for the reminder!
